spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 951389382479-7219qekhbk9jslj9llf9qq1skm9pbrcp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


server:
  port: 8082